---

- name: "VCL {{name}} | Create"
  sudo: yes
  template:
    src: "{{template|default(name+'.vcl')}}"
    dest: "{{varnish_vcl_dir}}/{{name}}.vcl"
  when: state is not defined or state == 'present'
  notify: restart varnish
  tags:
    - conf
    - vcl
    - varnish
    - http-cache

- name: "VCL {{name}} | Remove"
  sudo: yes
  file:
    dest: "{{varnish_vcl_dir}}/{{name}}.vcl"
    state: absent
  when: state is defined and state == 'absent'
  notify: restart varnish
  tags:
    - conf
    - vcl
    - varnish
    - http-cache
