---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: us-east-1
    key_name: jeff
    image: ami-d05e75b8
  tasks:
    - name: server for es nginx staging
      ec2:
        region: us-east-1
        image: "{{ image }}"
        instance_type: m3.large
        group_id: sg-fb38f99d
        vpc_subnet_id: subnet-5df60d76
        assign_public_ip:  yes
        key_name: "{{key_name}}"
        instance_tags:
          Name: Nginx for ES Staging
          Application: ES
          Environment: Staging
        count_tag:
          Name: Nginx for ES Staging
          Environment: Staging
        register: ec2
    - name: allocate elastic ip
      ec2_ip: "instance_id={{ item }}"
      with_items: ec2.instance_ids
      register: eip
    - name: add server to contentlycontrol.com
      route53:
        command: create
        zone: contentlycontrol.com
        record: es-staging.contentlycontrol.com
        type: A
        ttl: 7200
        value: "{{ item.public_ip }}"
      with_items: eip.results
      tags: "nginx-server"

    - name: server for ES Master
      ec2:
        region: "{{region}}"
        image: "{{image}}"
        instance_type: c3.xlarge
        group_id: sg-e237f684
        vpc_subnet_id: subnet-5ef60d75
        wait: yes
        key_name: contently-vpc

    - name: server for ES data
      ec2:
        region: "{{region}}"
        image: "{{image}}"
        instance_type: r3.xlarge
        vpc_subnet_id: subnet-5ef60d75
        wait: yes
        group_id: sg-e237f684
        key_name: contently-vpc
        instance_tags:
          Name: ES-DATA
          Environment: Staging
        volumes:
          - device_name: /dev/sdb
            volume_size: 200
      tags: "data"
