---
- hosts: nginx-staging
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/elasticsearch.yml
  tasks:
    - name: update cache
      apt: update_cache=yes
    - name: install nginx
      apt: pkg={{ item }} state=latest
      with_items:
        - htop
        - nginx
        - ntp
  roles:
    - elasticsearch

