---
- name: Provision EC2 Box
  ec2:
    group_id: "{{ group_id }}"
    key_name: "{{ key_name }}"
    image: "{{ image }}"
    region: "{{ region }}"
    instance_type: "{{ instance_type }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    ec2_tag_Name: "{{ ec2_tag_Name }}"
    ec2_tag_Environment: "ec2_tag_Environment"
    ec2_tag_Type: "{{ ec2_tag_Type }}"
    assign_public_ip: yes
    group_id: "{{ group_id }}"
    key_name: "{{ key_name }}"
    image: "{{ image }}"
    instance_type: "{{ instance_type }}"
    wait: true
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    instance_tags: '{"Name":"{{ec2_tag_Name}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
    count: 1
    volumes:
    - device_name: /dev/sda1
      device_type: gp2
      volume_size: 20
      delete_on_terminatioin: true
  register: ec2

- debug: var=item
  with_items: ec2.instances

- add_host: name={{ item.public_ip }} >
            groups=tag_Type_{{ec2_tag_type}}, tag_Environment_{{ec2_tag_Environment}}
            ec2_region={{ec2_region}}
            ec2_tag_Name={{ec2_tag_Name}}
            ec2_tag_Type={{ec2_tag_Type}}
            ec2_tag_Environment={{ec2_tag_Environment}}
            ec2_ip_address={{item.public_ip}}
  with_items: ec2.instances

- name: Wait for the instance to boot
  wait_for: host={{ item.public.ip}} port=22 delay=60 timeout=120 state=started
  with_items: ec2.instances

- name: set the sever up
  hosts: Webserver
  user: ubuntu
  sudo: yes
  roles:
    - nginx-elb
    - varnish

