---
- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    region: us-east-1
    instance_type: m3.medium
    image: ami-d05e75b8
    subnet_id: subnet-dc269885
    group_id: sg-b7aeeed0
    keyname: jeff
  tasks:
    - name: Elastic Search Servers
      ec2:
        key_name: "{{ keyname }}"
        group_id: "{{ group_id}}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        count: 1
        instance_tags:
          Name: elastic_nginx
          env: Production
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
      register: ec2
    - name: Add new hosts to host group
      add_host: hostname={{ item.public_ip }} groupname=ES
      with_items: ec2.instances
    - name: wait for ssh to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances


