- name: Add Docker repository key
  apt_key: url="https://get.docker.io/gpg" id="A88D21E9"

- name: Add Docker repository
  apt_repository:
    repo: 'deb http://get.docker.io/ubuntu docker main'
    update_cache: yes
  sudo: yes

- name: update apt cache
  apt: update_cache=yes
  sudo: yes

- name: Upgrade packages
  apt: upgrade=dist
  sudo: yes

- name: Security Updates
  apt: pkg=unattended-upgrades state=present
  sudo: yes

- name: Install Docker
  apt: pkg=lxc-docker
  notify: "Start Docker"
  sudo: yes
