- name: Install nginx
  action: apt pkg=nginx state=latest
  notify:
    - start nginx

- name: write nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: remove default nginx site
  action: file path=/etc/nginx/sites-enabled/default state=absent

- name: start nginx at boot
  action: service name=nginx enabled=yes
